### ISSUE TITLE
Milk Bottle: Conflict between Neapolitan, Farmer's Delight, and FD add-ons

### ISSUE THREAD

**Issue by RegulusMasamune** [team-abnormals/abnormals-delight#109]
The Neapolitan milk bottle seems to not be tagged the same way the Farmer's Delight one is, making certain recipes from other Farmer's Delight add on mods impossible to craft, as they require the Farmer's Delight milk bottle, and won't accept the Nea one.

**Comment by bageldotjpg** [comment]
Farmer's delight bottle should tag itself as `forge:bottles/milk` and the add-ons should be using that instead of directly referencing the FD bottle
