### ISSUE TITLE
Abnormal Delight has class loading errors

### ISSUE THREAD

**Issue by DerSlenderman** [team-abnormals/abnormals-delight#18]
I try to make a modpack for an Twitch stream project and tumbled upon Abnormal.
The modpack is version 1.16.4 and there shouldn't be any problems, but every time I try to start the modpach I get the same error:
![image](https://user-images.githubusercontent.com/83375858/116477567-17497300-a87d-11eb-928f-90338c70b17a.png)

[Crash Report.txt](https://github.com/team-abnormals/abnormals-delight/files/6395013/Crash.Report.txt)

The mods I use are the following:
![image](https://user-images.githubusercontent.com/83375858/116477780-5e376880-a87d-11eb-8f11-47cbb149c91d.png)

If the mod files are needed I can upload them on google drive and send a public link...

**Comment by DerSlenderman** [comment]
I forgot to mention, that the problem persists, even if I switch to the newer abnormal delight version

**Comment by bageldotjpg** [comment]
Your Farmer's Delight version is insanely outdated. Go to latest Farmer's Delight version and latest Abnormals Delight version.
Also I reccomend using 1.16.5 as all 1.16.4 mods work on 1.16.5 but not all 1.16.5 mods work on 1.16.4.
