### ISSUE TITLE
[Suggestion] Support for Seasonals and Peculiars

### ISSUE THREAD

**Issue by Minothilos** [team-abnormals/abnormals-delight#2]
I'm so happy to see this mod come into exsistance since I love the Abnormals package and Farmer's Delight. I was wondering if you could add support for the Neapolitan add-ons Seasonals and Peculiars. I know they're not really "abnormals mods" but they add some cakes and it would be nice if they were slicable as well.

Thanks again!

**Comment by bageldotjpg** [comment]
Unfortunately, we currently have no plans for supporting other mods
