### ISSUE TITLE
Rice JEI Recipe Game Breaking Crash

### ISSUE THREAD

**Issue by RedTheMask** [team-abnormals/abnormals-delight#25]
if you have JEI installed and right click rice to see what it makes, and you go to the cooking pot tab it will either instantly crash the game, or say there are 3 pages instead of 2 and when you go to the 3rd page, then it crashes. There may be other glitches like this but i only know it happens to rice

**Comment by beanaboston** [comment]
Also having this issue in the modpack Crucial 2. Using the latest version of Abnormal's Delights (1.1.1).

https://paste.ee/p/GwjdJ

**Comment by cosmicgelatin** [comment]
This also happens when checking Inc Sac's cooking recipes, because there's a leftover recipe for Squid Ink Risotto in the most recent release. Farmer's Delight apparently doesn't like recipes for nonexistent items, and crashes because of it. This looks fixed indev.

**Comment by bageldotjpg** [comment]
Should be fixed as of the latest release
