### ISSUE TITLE
Cooking Pot foods don't stack up to 16

### ISSUE THREAD

**Issue by Kisutora** [team-abnormals/abnormals-delight#3]
Abnormals foods don't match with Farmer's Delight food stack limit of 16.
![image](https://user-images.githubusercontent.com/22685232/109545133-1db3ac80-7ad1-11eb-96c0-5abc829a66d3.png)
**List of foods:**
Squid Ink Risotto
Scrambled Eggs
Adzuki Curry
Adzuki Stew

**Comment by bageldotjpg** [comment]
That will be possible in the next Farmer's Delight update, I think you already reported that there
