### ISSUE TITLE
[Suggestion] Unify "Rice" between Environmental and Farmer's Delight

### ISSUE THREAD

**Issue by xlea99** [team-abnormals/abnormals-delight#4]
Hello! I just noticed that at the moment, Rice is an item that's available in both Farmer's Delight and Environmental. For consistency's sake, would it be possible for this mod to remove one in favor of the other? That way all rice related recipes from both mods would use just one mod's item.

Thanks for reading!

**Comment by bageldotjpg** [comment]
You can disable environmental's rice in the environmental config
