### ISSUE TITLE
SUGGESTION: Incubation fried egg compatibility with Farmer's Delight

### ISSUE THREAD

**Issue by Tsunamori74** [team-abnormals/abnormals-delight#42]
This could be handled in two ways, either make the Incubation fried egg interchangeable with the FD fried egg in recipes, or (in my opinion the better option) disable the Incubation fried egg altogether if FD is detected. I always thought it was a bit strange how Abnormals Delight overlooked this.

**Comment by bageldotjpg** [comment]
Should work as of latest incubation
