### ISSUE TITLE
Odd Crash on 1.16

### ISSUE THREAD

**Issue by Velkheim01** [team-abnormals/abnormals-delight#45]
Hi, 
I want to start off by saying that I love using the Abnormals mods and they are staples whenever I play modded minecraft. Keep up the good work!  I started up a new custom modpack and it gave me this crash; it mentioned the abnormals delight config being accessed by two processes at once.
[crash-2022-07-24_17.10.33-client.txt](https://github.com/team-abnormals/abnormals-delight/files/9176762/crash-2022-07-24_17.10.33-client.txt)

**Comment by bageldotjpg** [comment]
This sounds like something on your computers end
