### ISSUE TITLE
crash when eating strawberry acka

### ISSUE THREAD

**Issue by thelegitdolt** [team-abnormals/abnormals-delight#50]
https://gist.github.com/thelegitdolt/08f2e9d77a68229893c8ddb437dc3e88

**Comment by thelegitdolt** [comment]
slice. strawberry cake slice

**Comment by LilJagty** [comment]
Hey, I just encountered the same issue playing on 1.18.2 on a Forge server with a few other mods. As soon as I tried to eat the strawberry cake slice, I got "Internal Server Error" and my I got DC'ed from the server, but my game didn't crash.

**Comment by LilJagty** [comment]
Devs, can we please get an update on this? It's a gamebreaking crash, and you've known about it since September 18th.

**Comment by Reshirou** [comment]
bump, it still happens, and on 1.19.2

**Comment by thelegitdolt** [comment]
wow
