### ISSUE TITLE
Cooking Pot recipes added by AD are not in their proper categories in the recipe book

### ISSUE THREAD

**Issue by thelegitdolt** [team-abnormals/abnormals-delight#60]
For example, cherry cream soda are not in the "drinks" tab on the the recipe book, even though they are a drink

**Comment by thelegitdolt** [comment]
<img width="1256" alt="Screen Shot 2023-02-06 at 12 45 32 PM" src="https://user-images.githubusercontent.com/50085439/217081255-f5a32d2c-ec81-44e0-8357-f513a4a0b7f1.png">
blrb

**Comment by bageldotjpg** [comment]
What is "and stuff"? Is it just that one? Create proper issue reports

**Comment by thelegitdolt** [comment]
i cba to find them all, if one's weird they probably all are, just letting you know the issue exists

**Comment by bageldotjpg** [comment]
If you aren't gonna be useful in your bug reports, don't bother reporting. You've been increasingly difficult lately, please begin to show some maturity. Every issue you've posted has been ridiculously informal and riddled with spelling errors, no elaboration, and other issues.

**Comment by thelegitdolt** [comment]
Apologies for the misunderstanding, let me edit the title to be clearer

i don't really elaborate unless I think elaboration is needed. if you're confused about them, please just ask away. Sorry I brushed you off earlier; I have posted issues like this in multiple githubs and have never gotten any pushback, and given the way you've treated me recently, I thought you were just singling me out for no reason. 

I personally don't intentionally try to make my issues formal because I feel like it doesn't really detract from their comprehensibility, but if it really matters that much to you, I can try my best 👍

**Comment by LaGz4643** [comment]
Recipes that should be in the "meals" tab:
- Duck Noodles
- Perch with Mushrooms
- Pike with Beetroot
- Venison with Bamboo Shoots
- Escargot
- Adzuki Curry
- Adzuki Stew
- Truffle Mash

Recipes that should be in the "drinks" tab:
- Cherry Cream Soda
- Passion Aloe Nectar
- Pickerelweed Juice

Recipes that should be in the "misc" tab:
- Foul Soup
- Slabdish
- Scrambled Eggs

**Comment by LaGz4643** [comment]
Scrambled Eggs and Escargot could go in either "meals" or "misc".
