### ISSUE TITLE
wrong display of raw/cooked turkey on cutting board

### ISSUE THREAD

**Issue by Aleruslio** [team-abnormals/abnormals-delight#64]
![image](https://user-images.githubusercontent.com/100682849/219857589-02ef6d34-e02b-44fb-be93-7992bdcb881b.png)
raw/cooked turkey (from autumnity) displays wrong on cutting board (from farmer's delight) (even without abnormals delight, but i dunno where i should post it - here or in autumnity branch)
Minecraft 1.18.2
Forge 40.2.1
Abnormals Delight 3.0.2
Autumnity 3.0.0
Farmer's Delight 1.2.0

**Comment by bageldotjpg** [comment]
Fixed in https://github.com/vectorwing/FarmersDelight/issues/408
