### ISSUE TITLE
Lava Lamps from Caverns & Chasms are not added to the `farmersdelight:heat_sources` block tag.

### ISSUE THREAD

**Issue by LaGz4643** [team-abnormals/abnormals-delight#75]
Lava Lamps are in the `farmersdelight:tray_heat_sources` tag but are not in the `farmersdelight:heat_sources` tag.

**Comment by bageldotjpg** [comment]
Yeah they are? `heat_sources` parents `tray_heat_sources`
They do not currently have the `tray_heat_sources` tag in any released version, but they will in the next patch (#74)
