### ISSUE TITLE
Barbecue stick recipe doesn't have any sticks in it

### ISSUE THREAD

**Issue by thelegitdolt** [team-abnormals/abnormals-delight#78]
In FD, the barbecue stick recipe uses a stick. But AD's overwritten version removes the stick. 

https://github.com/vectorwing/FarmersDelight/blob/1.19/src/generated/resources/data/farmersdelight/recipes/barbecue_stick.json
(stick) 

https://github.com/team-abnormals/abnormals-delight/blob/1.19.x/src/main/resources/data/farmersdelight/recipes/barbecue_stick.json
(No stick)

**Comment by bageldotjpg** [comment]
Fixed in d8d00ab7b77c24146d4e743731cf4f8e0eb23166
