### ISSUE TITLE
The mineable/axe tag contains blocks that don't exist, breaking axes.

### ISSUE THREAD

**Issue by brisingraerowing** [team-abnormals/abnormals-delight#80]
As per title. Several of the blocks listed in the tag don't exist, causing the tag to error.

**Comment by kittysmugglers** [comment]
bumping, also having this issue

**Comment by brisingraerowing** [comment]
Forgot about this issue. Turns out this mod wasn't my issue. It was Floor Mats. The latest FM update works, and I'm using this in a pack where Axes work.
