### ISSUE TITLE
1.19.2 Vanilla eggs incompatible for cooking

### ISSUE THREAD

**Issue by ExVonica** [team-abnormals/abnormals-delight#81]
When trying to use vanilla eggs to create recipes, it does not work. For example, when the skillet is put on the stove then you try to cook an egg (to make fried egg) it says this item isn't cookable. It also doesn't allow other recipes, such as roast chicken, to be created with vanilla eggs.

I reported bug to the Farmer's Delight issues Github page and they managed to find that the problem is from Abnormals delight. I'll paste what they said as well as link the original report I made there.

> "This seems to be an issue with Abnormals Delight: it attempts to disable Environmental's egg smelting recipes, but fails, causing both recipes to not be loaded"

Here is the link 
https://github.com/vectorwing/FarmersDelight/issues/665#event-9133317838

**Comment by bageldotjpg** [comment]
Fixed in https://github.com/team-abnormals/abnormals-delight/commit/3937d4d436c7498e8d0001d20d67f3cec7ead1d8
