### ISSUE TITLE
No Fried Egg recipe for Farmer's Delight

### ISSUE THREAD

**Issue by CircusSeal** [team-abnormals/abnormals-delight#86]
Originally posted in Farmer's Delight issues. I'll copy and paste the original post link here: https://github.com/vectorwing/FarmersDelight/issues/771

**Comment by bageldotjpg** [comment]
Fixed in https://github.com/team-abnormals/abnormals-delight/commit/3937d4d436c7498e8d0001d20d67f3cec7ead1d8
