### ISSUE TITLE
Missing compost pile structure of the Farmers Delight for Atmospheric's scrubland villages

### ISSUE THREAD

**Issue by Blunder-G** [team-abnormals/abnormals-delight#96]
There is currently no compost pile structure for scrubland villages made with Laurel and Morado woods. Farmers Delight adds a compost pile structure for every village type in vanilla.

**Comment by bageldotjpg** [comment]
Fixed in https://github.com/team-abnormals/atmospheric/commit/1a45e69f295e4aafd0bb2397efa3b53284217901
